set ( "${PROJECT_NAME}_VERSION_GENERATION" 0 )
set ( "${PROJECT_NAME}_VERSION_BRANCH" 0 )
set ( "${PROJECT_NAME}_VERSION_RELEASE" 0 )
set ( "${PROJECT_NAME}_VERSION_DEV" 1 )
set ( "${PROJECT_NAME}_VERSION" ${${PROJECT_NAME}_VERSION_GENERATION}.${${PROJECT_NAME}_VERSION_BRANCH}.${${PROJECT_NAME}_VERSION_RELEASE}.${${PROJECT_NAME}_VERSION_DEV} )
set ( "ver" ${${PROJECT_NAME}_VERSION_GENERATION}.${${PROJECT_NAME}_VERSION_BRANCH}.${${PROJECT_NAME}_VERSION_RELEASE}.${${PROJECT_NAME}_VERSION_DEV} )

set ( supported_languages CXX C )

set ( CMAKE_CXX_STANDARD 23 )

set ( "${PROJECT_NAME}_BINARY_DIR" bin )
set ( "${PROJECT_NAME}_SOURCE_DIR" src )
set ( "${PROJECT_NAME}_LIBS_DIR" libs )

set ( CMAKE_INCLUDE_PATH ${${PROJECT_NAME}_SOURCE_DIR} )
set ( CMAKE_LIBRARY_PATH ${${PROJECT_NAME}_LIBS_DIR} )
set ( EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${${PROJECT_NAME}_BINARY_DIR} )
#set ( LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${${PROJECT_NAME}_BINARY_DIR}/lib )
